package com.wb.mapper;

import com.wb.pojo.FunnelVO;
import com.wb.pojo.Tran;

import java.util.List;
import java.util.Map;

public interface TranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    int insert(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    int insertSelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    Tran selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    int updateByPrimaryKeySelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Mon May 16 11:26:29 CST 2022
     */
    int updateByPrimaryKey(Tran record);

    /**
     * 保存创建的交易
     * @param tran
     * @return
     */
    Integer insertTran(Tran tran);

    /**
     * 根据条件查询所有符合条件的交易信息
     * @return
     */
    List<Tran> selectAllTranByCon(Map<String,Object> map);

    /**
     * 根据条件查询总条数
     * @param map
     * @return
     */
    Integer selectCountByCon(Map<String,Object> map);

    /**
     * 根据主键查询交易详细信息
     * @param id
     * @return
     */
    Tran selectTranById(String id);

    /**
     * 查询交易表中各个阶段的交易数量
     * @return
     */
    List<FunnelVO> selectCountAllTranGroupByStage();
}